# Generated by Django 5.0.5 on 2024-05-07 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="decription",
            new_name="description",
        ),
    ]
